#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
#uri: https://github.com/bereketdeb/spring-cloud-config-server-repository.git
#username: bereketdeb@gmail.com
#password: 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